# Generated by Django 2.2.6 on 2020-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(choices=[('hyd', 'HYDERABAD'), ('bang', 'BANGALORE'), ('mum', 'MUMBAI'), ('che', 'CHENNAI')], default='hyd', max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstName',
            field=models.CharField(max_length=8),
        ),
    ]
